index:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: "index.html.twig"
    statusCode: 200
webcomponents:
  path: /webcomponents
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: /webcomponents/index.html.twig
mainpage:
  path: /mainpage
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: /mainpage/index.html.twig
